apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: config-demo
  name: config-demo
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      deploymentconfig: config-demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: config-demo
        deploymentconfig: config-demo
      name: config-demo
    spec:
      containers:
      - name: apache
        image: registry.access.redhat.com/ubi8/httpd-24:1-226
        #imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html
          name: config-demo-configmap
        - mountPath: /var/www/html/secret
          readOnly: true
          name: config-demo-secret
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: config-demo-configmap
        configMap:
          defaultMode: 438
          name: config-demo-configmap
      - name: config-demo-secret
        secret:
          secretName: config-demo-secret
