---
apiVersion: {{ .Values.esoversion }}
kind: ExternalSecret
metadata:
  name: config-demo-secret
  namespace: config-demo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: config-demo-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.configdemosecret.key }}
