{{- if .Values.global.useExternalSecrets }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: hypershift-eso-aws
  namespace: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: hypershift-operator-oidc-provider-s3-credentials
    template:
      mergePolicy: Merge
      type: Opaque
      data:
        region: {{ .Values.global.s3.region }}
        bucket: {{ .Values.global.s3.bucketName }}
  dataFrom:
  - extract:
      key: {{ .Values.awsCredentials.key }}
{{- end }}