---
global:
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
clusterGroup:
  name: region-one
  isHubCluster: false
  namespaces:
    - config-demo
    - hello-world
    - golang-external-secrets
  subscriptions:
    - name: web-terminal
      namespace: openshift-operators
      channel: fast
    - name: compliance-operator
      namespace: openshift-compliance
      channel: stable
    - name: gatekeeper-operator-product
      namespace: openshift-operators
      channel: stable

  projects:
    - eso
    - config-demo
    - hello-world
    - openshift-piplines
    - openshift-operators

  applications:
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: eso
      path: common/golang-external-secrets
    config-demo:
      name: config-demo
      namespace: config-demo
      project: config-demo
      path: charts/all/config-demo
    hello-world:
      name: hello-world
      namespace: hello-world
      project: hello-world
      path: charts/all/hello-world


    openshift-pipelines:
      name: openshift-pipelines
      namespace: openshift-pipelines
      project: openshift-pipelines
      path: charts/region/region-one/openshift-pipelines

    gatekeeper:
      name: gatekeeper
      namespace: gatekeeper-system
      project: gatekeeper-system
      path: common/gatekeeper

      #    acm-observability:
      #      name: acm-observability
      #      project: hub
      #      path: common/acm-observability

      #    acm-backup:
      #      name: acm-backup
      #      project: hub
      #      path: common/acm-backup

      #  managedClusterGroups:
      #    exampleRegion:
      #      name: group-one
      #      acmlabels:
      #        - name: clusterGroup
      #          value: group-one
      #      helmOverrides:
      #        - name: clusterGroup.isHubCluster
      #          value: false

      # Before enabling cluster provisioning, ensure AWS and/or Azure
      #   credentials and OCP pull secrets are defined in Vault.
      #   See values-secret.yaml.template
      #
      # clusterPools:
      #  exampleAWSPool:
      #    name: aws-ap
      #    openshiftVersion: 4.10.18
      #    baseDomain: blueprints.rhecoeng.com
      #    platform:
      #      aws:
      #        region: ap-southeast-2
      #    clusters:
      #    - One
      #
      #  exampleAzurePool:
      #    name: azure-us
      #    openshiftVersion: 4.10.18
      #    baseDomain: blueprints.rhecoeng.com
      #    platform:
      #      azure:
      #        baseDomainResourceGroupName: dojo-dns-zones
      #        region: eastus
      #    clusters:
      #    - Two
      #    - Three

      #  To have apps in multiple flavors, use namespaces
      #  and use helm overrides as appropriate
  imperative:
    # NOTE: We *must* use lists and not hashes.
    # As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs:
      - name: hello-world
        # ansible playbook to be run
        playbook: common/ansible/playbooks/hello-world/hello-world.yaml
        # per playbook timeout in seconds
        timeout: 234
        # verbosity: "-v"
  # Explicitly mention the cluster-state based
  # overrides we plan to use for this pattern.
  # We can use self-referential variables because the
  # chart calls the tpl function with these variables defined
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    # To mirror the "Classic" magic include structure,
    # the clusterGroup would need all of these:
    # sharedValueFiles:
    #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}-\
    #   {{ $.Values.global.clusterVersion }}.yaml'
    #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}-\
    #   {{ $.Values.clusterGroup.name }}.yaml'
    #   - '/overrides/values-{{ $.Values.global.clusterVersion }}-\
    #   {{ $.Values.clusterGroup.name }}.yaml"
#  To have apps in multiple flavors, use namespaces
#  and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main

#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: site.isHubCluster
#        value: false
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift
