{{- range .Values.secretsEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .name }}{{ .name }}{{ else }}{{ include "backend.fullname" $ }}-secret{{ end }}
  labels:
    {{- include "backend.labels" $ | nindent 4 }}
data:
{{- if kindIs "slice" .data }}
{{- range .data }}
  {{- if and (hasKey . "name") (hasKey . "path") }}
  {{ .name }}: |-
{{- $.Files.Get .path | nindent 4 | trimSuffix "\n" }}
  {{- end }}
{{- end }}
{{- else if kindIs "map" .data }}
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
---
{{- end }}