# Copyright (c) 2022 - 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
spec:
  extraLabelNs:
    - sgx.intel.com
  resourceLabels:
    - sgx.intel.com/epc
  operand:
    image: quay.io/openshift/origin-node-feature-discovery:4.13
    imagePullPolicy: Always
    servicePort: 12000
  workerConfig:
    configData: |
