---
# Eventually we should aim to move these two under the golangExternalSecrets key
mountPath: "hub"
mountRole: "hub-role"

golangExternalSecrets:
  # This controls how ESO connects to vault
  caProvider:
    enabled: true # If vault is exposed via a route that is signed by a non internal CA you might want to disable this
    hubCluster:
      type: ConfigMap
      name: kube-root-ca.crt
      key: ca.crt
      namespace: golang-external-secrets
    nonhubCluster:
      type: Secret
      name: hub-ca
      key: hub-kube-root-ca.crt
      namespace: imperative

global:
  hubClusterDomain: hub.example.com
  clusterDomain: foo.example.com

clusterGroup:
  isHubCluster: true

external-secrets:
  image:
    tag: v0.9.8-ubi
  webhook:
    image:
      tag: v0.9.8-ubi
  certController:
    image:
      tag: v0.9.8-ubi
