---
mountPath: "hub"
mountRole: "hub-role"

global:
  hubClusterDomain: hub.example.com
  clusterDomain: foo.example.com

clusterGroup:
  isHubCluster: true



external-secrets:
  image:
    tag: v0.7.2-ubi
  webhook:
    image:
      tag: v0.7.2-ubi
  certController:
    image:
      tag: v0.7.2-ubi
