---
golangExternalSecrets:
  rbac:
    rolename: "hub-role"

  kubernetes:
    remoteNamespace: "validated-patterns-secrets"
    server:
      url: 'https://kubernetes.default'

  vault:
    mountPath: "hub"

    # This controls how ESO connects to vault
  caProvider:
    enabled: true # If vault is exposed via a route that is signed by a non internal CA you might want to disable this
    hostCluster:
      type: ConfigMap
      name: kube-root-ca.crt
      key: ca.crt
      namespace: golang-external-secrets
    clientCluster:
      type: Secret
      name: hub-ca
      key: hub-kube-root-ca.crt
      namespace: imperative

global:
  hubClusterDomain: hub.example.com
  clusterDomain: foo.example.com

  secretStore:
    backend: "vault"

clusterGroup:
  isHubCluster: true

external-secrets:
  image:
    tag: v0.9.12-ubi
  webhook:
    image:
      tag: v0.9.12-ubi
  certController:
    image:
      tag: v0.9.12-ubi
