apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-{{ .Values.main.clusterGroupName }}
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: in-cluster
    namespace: {{ .Release.Name }}-{{ .Values.main.clusterGroupName }}
  project: default
  source:
    repoURL: {{ .Values.main.git.repoURL }}
    targetRevision: {{ .Values.main.git.revision }}
    path: common/clustergroup
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
      - "/values-global.yaml"
      - "/values-{{ .Values.main.clusterGroupName }}.yaml"
      # Track the progress of https://github.com/argoproj/argo-cd/pull/6280
      parameters:
        - name: global.repoURL
          value: $ARGOCD_APP_SOURCE_REPO_URL
        - name: global.targetRevision
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        - name: global.namespace
          value: $ARGOCD_APP_NAMESPACE
        - name: global.pattern
          value: {{ .Release.Name }}
        - name: global.hubClusterDomain
          value: {{ .Values.global.hubClusterDomain }}
        - name: vault.server.route.host
          value: {{ .Values.vault.server.route.host }}
{{- if eq .Values.main.options.syncPolicy "Automatic" }}
  syncPolicy:
    automated: {}
{{- end }}
