{{- range .Values.configmapEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ if .name }}{{ .name }}{{ else }}{{ include "openmetadata.fullname" $ }}-configmap{{ end }}
  labels:
    {{- include "openmetadata.labels" $ | nindent 4 }}
data:
{{- if kindIs "slice" .data }}
{{- range .data }}
  {{- if and (hasKey . "name") (hasKey . "path") }}
  {{ .name }}: |-
{{- $.Files.Get .path | nindent 4 | trimSuffix "\n" }}
  {{- end }}
{{- end }}
{{- else if kindIs "map" .data }}
{{- range $key, $value := .data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
---
{{- end }}