global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic
  multiClusterTarget: all

#enabled: all

clusterGroup:
  name: example
  #insecureUnsealVaultInsideCluster: false
  isHubCluster: true
  sharedValueFiles:
  - /values/{{ .Values.global.clusterPlatform }}.yaml
  - /values/{{ .Values.global.clusterVersion }}.yaml

  namespaces:
  - open-cluster-management:
      labels:
        openshift.io/node-selector: ""
        kubernetes.io/os: linux
      annotations:
        openshift.io/cluster-monitoring: "true"
        owner: "namespace owner"
  - application-ci
  - excludes-ci

  operatorgroupExcludes:
  - excludes-ci


  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.4
      csv: advanced-cluster-management.v2.4.1

    odh:
      name: opendatahub-operator
      source: community-operators
      csv: opendatahub-operator.v1.1.0
      disabled: true

    pipelines:
      name: openshift-pipelines-operator-rh
      csv: redhat-openshift-pipelines.v1.5.2

  projects:
  - datacenter

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: datacenter
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
        - /spec/loggingCA
    pipe:
      name: pipelines
      namespace: application-ci
      project: datacenter
      path: charts/datacenter/pipelines
      extraValueFiles:
      - /values/{{ .Values.global.clusterVersion }}/{{ .Values.global.clusterPlatform }}.yaml

  imperative:
    namespace: imperative
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs:
    - name: regional-ca
      # ansible playbook to be run
      playbook: ansible/playbooks/on-hub-get-regional-ca.yml
      # per playbook timeout in seconds
      timeout: 234
      # verbosity: "-v"

  managedClusterGroups:
  - name: acm-edge
    # Optional - Point to a different repo
    # repoURL: https://github.com/hybrid-cloud-patterns/mySite.git
    # Must contain values-{clustergroupname}.yaml at the top level
    targetRevision: main
    helmOverrides:
    # Values must be strings!
    - name: clusterGroup.isHubCluster
      value: "false"
    acmlabels:
    - name: clusterGroup
      value: acm-region
  - name: acm-provision-edge
    targetRevision: main
    helmOverrides:
    - name: clusterGroup.isHubCluster
      value: "false"
    clusterPools:
      exampleAWSPool:
        size: 3
        name: aws-ap
        openshiftVersion: 4.10.18
        baseDomain: blueprints.rhecoeng.com
        controlPlane:
          count: 1
          platform:
            aws:
              type: m5.xlarge
        workers:
          count: 0
        platform:
          aws:
            region: ap-southeast-2
      exampleAzurePool:
        name: azure-us
        openshiftVersion: 4.10.18
        baseDomain: blueprints.rhecoeng.com
        platform:
          azure:
            baseDomainResourceGroupName: dojo-dns-zones
            region: eastus
        clusters:
        - Two
        - three
    acmlabels:
    - name: clusterGroup
      value: region
  - name: argo-edge
    hostedArgoSites:
    - name: perth
      domain: perth1.beekhof.net
      # The default is secret/data/hub/cluster_<name>
      #secretsPath: secret/data/hub/cluster_perth
    - name: sydney
      domain: syd.beekhof.net
      # The default is secret/data/hub/cluster_<name>
      #secretsPath: secret/data/hub/cluster_sydney
    helmOverrides:
    - name: clusterGroup.isHubCluster
      value: "false"
