---
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

esoversion: "external-secrets.io/v1beta1"
configdemosecret:
  key: secret/data/global/config-demo

global:
  hubClusterDomain: hub.example.com
  localClusterDomain: region-one.example.com

clusterGroup:
  isHubCluster: true
