{{- $valuesDirectoryURL :=  cat .Values.main.git.repoURL "/raw/" .Values.main.git.revision -}}
{{- $valuesDirectoryURLFixed :=  $valuesDirectoryURL | replace " " "" | replace ".git" "" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-{{ .Values.main.siteName }}
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: {{ .Values.main.siteName }}
  project: default
  source:
    repoURL: {{ .Values.main.git.repoURL }}
    targetRevision: {{ .Values.main.git.revision }}
    path: common/site
    helm:
      valueFiles:
      - "{{ coalesce .Values.main.git.valuesDirectoryURL $valuesDirectoryURLFixed }}/values-global.yaml"
      - "{{ coalesce .Values.main.git.valuesDirectoryURL $valuesDirectoryURLFixed }}/values-{{ .Values.main.siteName }}.yaml"
      # Track the progress of https://github.com/argoproj/argo-cd/pull/6280
      parameters:
        - name: global.repoURL
          value: $ARGOCD_APP_SOURCE_REPO_URL
        - name: global.targetRevision
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        - name: global.namespace
          value: $ARGOCD_APP_NAMESPACE
        - name: global.valuesDirectoryURL
          value: {{ coalesce .Values.main.git.valuesDirectoryURL $valuesDirectoryURLFixed }}
        - name: global.pattern
          value: {{ .Release.Name }}
{{- if eq .Values.main.options.syncPolicy "Automatic" }}
  syncPolicy:
    automated: {}
{{- end }}
