---
- include_tasks: pre_check.yaml
- include_tasks: vault_status.yaml

- name: Fail if the vault is sealed
  ansible.builtin.fail:
    msg: "The vault is still sealed, cannot continue"
  failed_when: vault_status['sealed'] | bool

- name: Check for existence of "{{ values_secret }}"
  ansible.builtin.stat:
    path: "{{ values_secret }}"
  register: result
  failed_when: not result.stat.exists

- name: Parse "{{ values_secret }}"
  ansible.builtin.set_fact:
    all_values: "{{ lookup('file', values_secret) | from_yaml | default({}, true) }}"

- name: Check for secrets keys
  ansible.builtin.fail:
    msg: "Was not able to parse any secrets from file {{ values_secret }}. 'secrets:' top-level key is missing"
  failed_when: "'secrets' not in all_values.keys()"

- name: Set secrets fact
  ansible.builtin.set_fact:
    secrets: "{{ all_values['secrets'] }}"

- name: Verify we have any secrets at all
  ansible.builtin.fail:
    msg: "Was not able to parse any secrets from file {{ values_secret }}: {{ all_values }}"
  failed_when:
    secrets is not defined or secrets | length == 0

- name: Check the value-secret.yaml file for errors
  ansible.builtin.fail:
    msg: >
      "{{ item }}" is not properly formatted. Each key under 'secrets:'
      needs to point to a dictionary of key, value pairs. See values-secret.yaml.template.
  when: >
    item.key | length == 0 or
    item.value is not mapping
  loop:
    "{{ secrets | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Check the value-secret.yaml file for errors
  ansible.builtin.fail:
    msg: >
      "{{ item }}" is not properly formatted. Each key under 'secrets:'
      needs to point to a dictionary of key, value pairs. See values-secret.yaml.template.
  when: >
    item.key | length == 0 or
    item.value is not mapping
  loop:
    "{{ secrets | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

# Detect here if we have only the following two keys under a password
# s3.accessKey: <accessKey>
# s3.secretKey: <secret key>
# If we do, then detect it and calculate the b64 s3Secret token
# Note: the vars: line is due to https://github.com/ansible/ansible/issues/40239
- name: Check if any of the passwords has only s3.[accessKey,secretKey] and generate the combined s3Secret in that case
  ansible.builtin.set_fact:
    s3keys: "{{ s3keys | default({}) | combine({ item.key: {'s3Secret': s3secret | b64encode } }) }}"
  vars:
    s3secret: "{{ 's3.accessKey: ' + item.value['s3.accessKey'] + '\ns3.secretKey: ' + item.value['s3.secretKey'] }}"
  when:
    - '"s3.accessKey" in item.value.keys()'
    - '"s3.secretKey" in item.value.keys()'
    - '"s3Secret" not in item.value.keys()'
  loop:
    "{{ secrets | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Merge any s3Secret into the secrets dictionary if we have any
  ansible.builtin.set_fact:
    secrets: "{{ secrets | combine(s3keys) }}"
  when:
    s3keys is defined and s3keys | length > 0

# The values-secret.yaml file is in the fairly loose form of:
# secrets:
#   group1:
#     key1: value1
#     key2: value2
#   group2:
#     key1: valueA
#     key4: valueC
# The above will generate:
# vault kv put 'secret/hub/group1' key1='value1' key2='value2'
# vault kv put 'secret/hub/group2' key1='valueA' key4='valueC'
# Below we loop on the top level keys (group1, group2) and for each
# sub-top-level key (key1, key2) we create a single 'key1=value1 key2=value2' string
#
# Special note is to be given to the regex_replace which is run against each value aka password:
# A. The need for it is to quote the passwords
# B. Since it needs to cater to multiline strings (certs) and ansible offers no way
#    to specify re.DOTALL and re.MULTILINE we need to use (?ms) at the beginning
#    See https://docs.python.org/3/library/re.html and (?aiLmsux) section
#    and https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/core.py#L124
# C. The \\A and \\Z match the beginning and end of a string (in case of multiline strings
#    do not want to match every line)
- name: Set vault commands fact
  ansible.builtin.set_fact:
    vault_cmds: "{{ vault_cmds | default({}) | combine({ item.key: vault_cmd}) }}"
  vars:
    vault_cmd: "vault kv put '{{ vault_path }}/{{ item.key }}'
      {{ item.value.keys() | zip(item.value.values() | map('regex_replace', '(?ms)\\A(.*)\\Z', \"'\\1'\")) | map('join', '=') | list | join(' ') }}"
  loop:
    "{{ secrets | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Debug vault commands
  ansible.builtin.debug:
    msg: "{{ vault_cmds }}"
  when: debug | default(False) | bool

- name: Add the actual secrets to the vault
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: |
      sh -c "{{ item.value }}"
  loop:
    "{{ vault_cmds | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: not debug | default(False) | bool
