---
- include_tasks: pre_check.yaml

- name: Is secrets backend already enabled
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: >
      bash -e -c "vault secrets list | grep -e '^{{ vault_base_path }}'"
  register: secrets_enabled
  failed_when: false

- name: Create secrets backend kv-v2
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: vault secrets enable -path="{{ vault_base_path }}" kv-v2
  when: secrets_enabled.rc != 0

- name: Is kubernetes backend already enabled
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: >
      bash -e -c "vault auth list | grep -e '^{{ vault_hub }}'"
  register: kubernetes_enabled
  failed_when: false

- name: Enable kubernetes backend on hub
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: "vault auth enable -path={{ vault_hub }} kubernetes"
  when: kubernetes_enabled.rc != 0

- name: Fetch "{{ external_secrets_ns }}/{{ external_secrets_sa }} secret name"
  ansible.builtin.shell: |
    oc get -n "{{ external_secrets_ns }}" serviceaccount "{{ external_secrets_sa }}" -o jsonpath='{.secrets}'
  register: secrets_out
  changed_when: true

- name: Filter secrets of "{{ external_secrets_ns }}/{{ external_secrets_sa }}"
  ansible.builtin.set_fact:
    secret: "{{ secrets_out.stdout | from_json | json_query(\"[?starts_with(name, 'golang-external-secrets-token-')].name | [0]\") }}"

- name: Get token of "{{ external_secrets_ns }}/{{ external_secrets_sa }}"
  ansible.builtin.shell: |
    set -o pipefail
    oc get secret -n "{{ external_secrets_ns }}" "{{ secret }}" -o go-template="{{ '{{' }} .data.token | base64decode {{ '}}' }}"
  register: sa_token_out
  changed_when: true

- name: Set sa_token fact
  ansible.builtin.set_fact:
    sa_token: "{{ sa_token_out.stdout }}"

- name: Configure hub kubernetes backend
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: >
      vault write auth/"{{ vault_hub }}"/config token_reviewer_jwt="{{ sa_token }}"
        kubernetes_host="{{ vault_hub_kubernetes_host }}"
        kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        issuer=https://kubernetes.default.svc

- name: Configure policy template for hub
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: >
      bash -e -c "echo \"path \\\"secret/data/{{ vault_hub }}/*\\\" {
        capabilities = {{ vault_hub_capabilities }} }\" > /tmp/policy-{{ vault_hub }}.hcl"

- name: Configure policy for hub
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: "vault policy write {{ vault_hub }}-secret /tmp/policy-{{ vault_hub }}.hcl"

- name: Configure kubernetes role for hub
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: >
      vault write auth/"{{ vault_hub }}"/role/"{{ vault_hub }}"-role
        bound_service_account_names="{{ external_secrets_sa }}"
        bound_service_account_namespaces="{{ external_secrets_ns }}"
        policies="default,{{ vault_hub }}-secret" ttl="{{ vault_hub_ttl }}"
