# Note this workflow is only maintained in this repo
# It should be invoked from each chart's repo
#
# This invokes the workflow named 'publish-charts' in the umbrella repo
# It expects to have a secret called UMBRELLA_REPO_PAT which contains
# the GitHub token that has permissions to invoke workflows and commit code
# inside the umbrella-repo.
# The following fine-grained permissions were used in testing and were limited
# to the umbrella repo only:
# - Actions: r/w
# - Commit statuses: r/w
# - Contents: r/w
# - Deployments: r/w
# - Pages: r/w

name: vp-patterns/update-helm-repo
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  helmlint:
    uses: validatedpatterns/helm-charts/.github/workflows/helmlint.yml@main
    permissions:
      contents: read

  update-helm-repo:
    needs: [helmlint]
    runs-on: ubuntu-latest
    uses: validatedpatterns/helm-charts/.github/workflows/update-helm-repo.yml@main
    permissions:
      id-token: write
      contents: read
