---
- name: Vault pre checks
  ansible.builtin.include_tasks: pre_check.yaml
- name: Vault status check
  ansible.builtin.include_tasks: vault_status.yaml

# If the vault is already initialized we skip all the tasks below
- name: Is the vault initialized?
  ansible.builtin.set_fact:
    vault_initialized: "{{ vault_status['initialized'] | bool }}"

# We need to retry here because the vault service might be starting
# and can return a 500 internal server until its state is fully ready
- name: Init vault operator
  no_log: true
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: vault operator init -format=json
  register: vault_init_json_out
  until: vault_init_json_out is not failed
  retries: 10
  delay: 15
  when: not vault_initialized

- name: Set vault init output json fact
  no_log: true
  ansible.builtin.set_fact:
    vault_init_json: "{{ vault_init_json_out.stdout | from_json }}"
  when: not vault_initialized

# We store the the operator unseal keys and root token to a secret inside
# the cluster when the vault was not already initialized *and* when
# unseal_from_cluster is set to true
- name: Save vault operator output (into a secret inside the cluster)
  no_log: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ unseal_secret }}"
        namespace: "{{ unseal_namespace }}"
      data:
        vault_data_json: "{{ vault_init_json | to_nice_json | b64encode }}"
  when:
    - not vault_initialized
