name: Ansible Lint # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v3

      - name: Lint Ansible Playbook (common)
        uses: ansible/ansible-lint-action@v6
        # Let's point it to the path
        with:
          path: "common/ansible/"

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v6
        # Let's point it to the path
        with:
          path: "ansible/"
